name: Heroku Deploy

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      heroku_app_name:
        type: string
        required: true
      branch_name:
        type: string
        required: false
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_API_KEY_EMAIL:
        required: true

jobs:
  heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo || github.event.inputs.repo }}
          ref: ${{ inputs.branch_name }}

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ inputs.heroku_app_name }}
          heroku_email: ${{ secrets.HEROKU_API_KEY_EMAIL }}
          branch: ${{ inputs.branch_name }}
