name: Heroku Deploy

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      heroku_app_name:
        type: string
        required: true
      branch_name:
        type: string
        required: false
    secrets:
      HEROKU_API_KEY:
        required: true

jobs:
  heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo || github.event.inputs.repo }}
          ref: ${{ inputs.branch_name }}

      - name: Deploy to Heroku
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.8
        with:
          herokuApiKey: ${{ secrets.HEROKU_API_KEY }}
          herokuAppName: ${{ inputs.heroku_app_name }}
          branch: ${{ inputs.branch_name }}
