# This action uses parity gem to execute `review restore_from staging`
# on the Heroku server.
name: Reset review database on Heroku

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      staging_remote:
        type: string
        required: true
      review_remote:
        type: string
        required: true
      heroku_app_name:
        type: string
        required: true
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_API_KEY_EMAIL:
        required: true

jobs:
  heroku:
    name: "Restore Heroku Review DB from Staging"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo || github.event.inputs.repo }}
          ref: ${{ inputs.branch_name }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku Login
        uses: akhileshns/heroku-deploy@v3.14.16
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ inputs.heroku_app_name }}
          heroku_email: ${{ secrets.HEROKU_API_KEY_EMAIL }}
          justlogin: true

      - name: Set Git Remote
        run: |
          git remote remove staging 2>/dev/null || true
          git remote remove review 2>/dev/null || true
          git remote add staging ${{ inputs.staging_remote }}
          git remote add review ${{ inputs.review_remote }}
          git remote -v

      - name: Restore Review DB from Staging
        run: |
          echo "Starting database restore..."
          bundle exec bin/review restore staging
          echo "Database restore complete."

      - name: Unset Git Remote
        run: |
          git remote remove staging || echo "Staging remote not found."
          git remote remove review || echo "Review remote not found."
